# Jekyll Options
safe:        true
auto:        true
server:      true
server_port: 4000
baseurl:     /ckan-style/
url:         http://localhost:4000

source:      .
destination: /tmp/ckan-styleguide
exclude:     [README.md]
future:      true
lsi:         false
pygments:    true
markdown:    kramdown
permalink:   /:title
kramdown:    {toc_levels: [2]}
